
name: Variables and Secrets in GitHub Actions

on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:
env:
  author: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      baseapi: http://baseurl.api/
    steps:
      - name: All Type of Varialbes and Secrets
        run: 
          echo "Workflow Variable | $author has created the api $baseapi which will expire in $expire"
          echo "Configuration Variable | Version of App is ${{ vars.version }}"
          echo "Secret | Secret Key is ${{ secrets.KEY }}"
          ${{secrets.KEY_VISIBLE}}
          echo "Context Variables | Repo Name is ${{ github.repository }}"
        env:
          expire: 10days